### ISSUE TITLE
focus does not work correctly on objects with offset registration points that are then rotated

### ISSUE THREAD

**Issue by rob-bateman** [awaytools/AwayBuilder#131]
**Steps to Reproduce**
- load up sponza.awd
- select the roof
- rotate -90 around the z axis
- click the focus button

**Expected result**

Camera adjusts position and zoom to focus on the new position of the roof

**Actual result**

Camera adjusts position and zoom to focus on the previous position of the roof

**Comment by rob-bateman** [comment]
This still appears to be a problem if, instead of rotating -90 degrees around the z axis, you offset the z position by 2000 and then press focus

**Comment by Greg209** [comment]
Fixed - needs updated Away3d engine too

**Comment by rob-bateman** [comment]
still doesn't work for me. In fact if anything, it appears to have got worse...

**Comment by rob-bateman** [comment]
that seems to have got it ;)
